backend:
   name: github # or gitlab
   repo: The-Union-of-Democratic-States/graphics
   branch: main
   base_url: https://sveltia-cms-auth.jaybeanstalk.workers.dev/
media_folder: "static/images/uploads"
collections:
  - label: "Dispatch"
    name: "dispatch"
    folder: "_dispatch/"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Resolution"
    name: "resolution"
    folder: "_resolution/"
    create: true
    fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Number", name: "number", widget: "string"}
        - {label: "Date Introduced", name: "date_introduced", widget: "datetime"}
        - {label: "Date Final", name: "date_final", widget: "datetime", required: false}
        - {label: "Chamber", name: "chamber", widget: "select", options: ["Council of State","General Assembly"]
        - {label: "Author", name: "author", widget: "relation", multiple: true , collection: "citizen", value_field: "nation_name"}
        - {label: "Text", name: "text", widget: "markdown"}
  - label: "Law"
    name: "law"
    folder: "_law/"
    create: true
    fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Number", name: "number", widget: "string"}
        - {label: "Text", name: "text", widget: "markdown"}
        - {label: "Versions", name: "versions", widget: "relation", multiple: true , collection: "resolution", value_field: "title"}
  - label: "Citizen"
    name: "citizen"
    folder: "_citizen/"
    create: true
    fields: 
       - {label: "Nation Name", name: "nation_name", widget: "string"}
       - {label: "World Assembly Status", name: "wa_status", widget: "select", options: ["Member", "Non-Nember"]}
  - label: "Order"
    name: "order"
    folder: "_order/"
    create: true
    fields: 
      - {label: "Office", name: "office", widget: "select", options: ["Presidency", "Chancery", "Governorate", "Delegacy"]}
      - {label: "Number", name: "number", widget: "string"}
      - {label: "Date Issued", name: "date_issued", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string:}
      - {label: "Author", name: "author", widget: "relation", multiple: true , collection: "citizen", value_field: "nation_name"}
      - {label: "Text", name: "text", widget: "markdown"}
  - label: "Default"
    name: "default"
    folder: "_default/"
    create: true
    fields: 
        - label: "Sections"
          name: "sections"
          widget: "list"
          fields: 
           - {label: "Title", name: "title", widget: "string"
           - {label: "Text", name: "text", widget: "markdown"
        - {label: "Title", name: "title", widget: "string"}
  - label: "Press Release"
    name: "press_release"
    folder: "_press_release/"
    create: true
    fields:
         - {label: "Title", name: "title", widget: "string"}
         - {label: "Date Published", name: "date_published", widget: "datetime", optional: true}
         - {label: "Subtitle", name: "subtitle", widget: "string", optional: true}
         - {label: "Office", name: "office", widget: "select", options: ["Ministry of Foreign Affairs", "Ministry of Defense"], optional: true}
      
